version: '3'

services:
  spark-master:
    image: apache/spark:${SPARK_VERSION}
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./logs:${LOGS_DIR}
      - ./workspace:${WORK_DIR}
    environment:
      - SPARK_MODE=master
    networks:
      spark-net:
    command: >
      bash -c "../sbin/start-master.sh;
      tail -f /dev/null"
    # command: ../bin/spark-class org.apache.spark.deploy.master.Master
    
  spark-worker-1:
    image: apache/spark:${SPARK_VERSION}
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    volumes:
      - ./logs:${LOGS_DIR}
      - ./workspace:${WORK_DIR}
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      # - SPARK_LOCAL_IP=127.0.0.1
    ports:
      - 8081:8081
    networks:
      - spark-net
    command: >
      bash -c "../sbin/start-worker.sh spark://spark-master:7077;
      tail -f /dev/null"
    # command: ../bin/spark-class org.apache.spark.deploy.worker.Worker

  spark-worker-2:
    image: apache/spark:${SPARK_VERSION}
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    volumes:
      - ./logs:${LOGS_DIR}
      - ./workspace:${WORK_DIR}
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      # - SPARK_LOCAL_IP=127.0.0.1
    ports:
      - 8082:8081
    networks:
      - spark-net
    command: >
      bash -c "../sbin/start-worker.sh spark://spark-master:7077;
      tail -f /dev/null"
    # command: ../bin/spark-class org.apache.spark.deploy.worker.Worker
  # jupyter-lab:
  #   image: jupyter-lab:${JUPYTERLAB_VERSION}
  #   container_name: jupyter-lab
  #   hostname: jupyter-lab
  #   ports:
  #     - 8888:8888
  #     - 4040:4040
  #   networks:
  #     - spark-net
  #   volumes:
  #     - ./workspace:${WORK_DIR}
  #   depends_on:
  #     - spark-master
networks:
  spark-net:
    name: spark-net
